modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="lands_of_renguard"
version="1.0.0"
displayName="Lands of Renguard"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="jsims, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.lands_of_renguard]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



